export { HomePage } from './HomePage/HomePage'
export { LoanPage } from './LoanPage/LoanPage'
export { NotFoundPage } from './NotFound/NotFoundPage'
export { ScoringPage } from './ScoringPage'
export { DocumentPage } from './DocumentPage'
export { SignPage } from './SignPage'
export { CodePage } from './CodePage'
